<h1>Home Page</h1>
<?php if (isset($flash['error'])): ?>
    <?php foreach ($flash['error'] as $message): ?>
        <div><p style="color: red"><?= $message; ?></p></div>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (isset($flash['success'])): ?>
    <?php foreach ($flash['success'] as $message): ?>
        <div><p style="color: green"><?= $message; ?></p></div>
    <?php endforeach; ?>
<?php endif; ?>

<?php if (!$isAuth): ?>
    <h2>Sign In</h2>
    <form action="/login" method="post">
        <div>
            <label>
                Email
                <input type="text" name="email">
            </label>
        </div>
        <input type="submit" value="Sign In">
    </form>
<?php else: ?>
    <a href="/users">Users Page</a>
    <hr>
    <form action="/logout" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Logout">
    </form>
<?php endif; ?>