<h1>New User</h1>
<a href="/users">Users Page</a>
<hr>
<form action="/users" method="post">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']); ?>">
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <div><?= $errors['nickname']; ?></div>
        <?php endif; ?>
    </div>
    <div>
        <label>
            Email:
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email']); ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email']; ?></div>
        <?php endif; ?>
    </div>
    <input type="submit" value="Create user">
</form>